// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

using System.Collections.Immutable;

namespace Elastic.Mapping.Generator.Model;

/// <summary>
/// Represents a complete AI enrichment configuration for a document type,
/// extracted from <c>[AiEnrichment&lt;T&gt;]</c> + <c>[AiInput]</c> / <c>[AiField]</c> declarations.
/// </summary>
internal sealed record AiEnrichmentModel(
	string DocumentTypeName,
	string DocumentTypeFullyQualifiedName,
	string? Role,
	string? LookupIndexName,
	/// <summary>
	/// The write alias from the <c>[Index&lt;T&gt;]</c> registration for the same document type.
	/// Used to derive the default lookup index name when <see cref="LookupIndexName"/> is null.
	/// </summary>
	string? WriteAlias,
	string MatchFieldName,
	ImmutableArray<AiInputFieldModel> Inputs,
	ImmutableArray<AiOutputFieldModel> Outputs
);

/// <summary>
/// An <c>[AiInput]</c> property — read from the document source to build the LLM prompt.
/// </summary>
internal sealed record AiInputFieldModel(
	string PropertyName,
	string FieldName
);

/// <summary>
/// An <c>[AiField]</c> property — generated by the LLM, stored in the lookup index.
/// </summary>
internal sealed record AiOutputFieldModel(
	string PropertyName,
	string FieldName,
	string Description,
	bool IsArray,
	int MinItems,
	int MaxItems,
	string PromptHash,
	string PromptHashFieldName
);
