<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Elastic.Channels\Elastic.Channels.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsCheck" Version="4.9.1" />
  </ItemGroup>

</Project>
