// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

namespace Elastic.Mapping;

/// <summary>
/// Registers an AI enrichment configuration on the mapping context for the specified document type.
/// The source generator produces an <c>IAiEnrichmentProvider</c> implementation with prompt building,
/// per-field response parsing, lookup index schema, enrich policy, and ingest pipeline definitions.
/// <para>
/// The document type is scanned for <see cref="AiInputAttribute"/> (fields used to build the LLM prompt)
/// and <see cref="AiFieldAttribute"/> (fields generated by the LLM).
/// </para>
/// </summary>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class AiEnrichmentAttribute<TDocument> : Attribute
	where TDocument : class
{
	/// <summary>
	/// Optional role preamble injected at the top of the generated prompt.
	/// </summary>
	public string? Role { get; init; }

	/// <summary>
	/// Lookup index name override. Defaults to <c>{write-alias}-ai-enrichment-cache</c>.
	/// </summary>
	public string? LookupIndexName { get; init; }

	/// <summary>
	/// The document field used as the match key between the lookup index and documents.
	/// Defaults to <c>"url"</c>.
	/// </summary>
	public string? MatchField { get; init; }
}
